### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by imruljubair** [WuJunde/MedSegDiff#117]
**I am trying to run the code on AWS SageMaker StudioLab. But I am getting error "ConnectionRefusedError: [Errno 111] Connection refused". The message is shown below. Can anyone please help?**

`python scripts/segmentation_train.py --data_name ISIC --data_dir input data direction --out_dir output data direction --image_size 256 --num_channels 128 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --lr 1e-4 --batch_size 8`

```
Setting up a new session...
Exception in user code:
```
```
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fee428c0e80>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8850): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee428c0e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by maralzar** [comment]
you should run visdom :
python -m visdom.server -port port_num
check port in code

**Comment by imruljubair** [comment]
> you should run visdom : python -m visdom.server -port port_num check port in code

Thank you so much :)

**Comment by Hangiscoming** [comment]
> > you should run visdom : python -m visdom.server -port port_num check port in code
> 
> Thank you so much :)



May I ask if this solution is effective？
