### ISSUE TITLE
An error will be reported when the image size is set to 512

### ISSUE THREAD

**Issue by PANPEIWEN** [WuJunde/MedSegDiff#30]
this error will occur
Original Traceback (most recent call last):
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 775, in forward
    uemb, cal = self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]])
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 744, in highway_forward
    return self.hwm(x,hs)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 2152, in forward
    h = self.ffparser[d](h)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 479, in forward
    x = x * weight
RuntimeError: The size of tensor a (129) must match the size of tensor b (65) at non-singleton dimension 3

**Comment by WuJunde** [comment]
you can train it with image size = 256 first, I will fix it soon.

**Comment by saisusmitha** [comment]
@WuJunde kindly let me know how to extract hd95, Jaccard, dice metrics, the code, and where to integrate that code - and is there any validation part code kindly share it?

**Comment by WuJunde** [comment]
evaluation code has been updated
