### ISSUE TITLE
When args.in_ch = 5, the following error will occur

### ISSUE THREAD

**Issue by PANPEIWEN** [WuJunde/MedSegDiff#32]
Original Traceback (most recent call last):
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 773, in forward
    h = module(h, emb)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/works/MedSegDiff/guided_diffusion/unet.py", line 86, in forward
    x = layer(x)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data1/ppw/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 5, 3, 3], expected input[8, 4, 256, 256] to have 5 channels, but got 4 channels instead

**Comment by Saharsh1005** [comment]
Based on my understanding, the data you are using is 2D. So the tensor shape of input baches wold be:
(Bach_size,channels, H, W) 
Hence args.in_ch should be 4 (and not 5 in that case)

Hope this helps!
