### ISSUE TITLE
about the training

### ISSUE THREAD

**Issue by jaceqin** [WuJunde/MedSegDiff#41]
When I running the scripts/segmentation_train.py have a problem.

Traceback (most recent call last):
  File "D:\jace\pythonProject\MedSegDiffv2-master\scripts\segmentation_train.py", line 110, in <module>
    main()
  File "D:\jace\pythonProject\MedSegDiffv2-master\scripts\segmentation_train.py", line 62, in main
    TrainLoop(
  File "D:\jace\pythonProject\MedSegDiffv2-master\guided_diffusion\train_util.py", line 83, in __init__
    self._load_and_sync_parameters()
  File "D:\jace\pythonProject\MedSegDiffv2-master\guided_diffusion\train_util.py", line 139, in _load_and_sync_parameters
    dist_util.sync_params(self.model.parameters())
  File "D:\jace\pythonProject\MedSegDiffv2-master\guided_diffusion\dist_util.py", line 78, in sync_params
    dist.broadcast(p, 0)
  File "C:\SoftWare\python 3.10\lib\site-packages\torch\distributed\distributed_c10d.py", line 1408, in broadcast
    work.wait()
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by 170744039** [comment]
Hello, I have also encountered this problem. Have you resolved it?
