### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by DWBSIC** [WuJunde/MedSegDiff#88]
Traceback (most recent call last):
  File "D:\MedSegDiff-master\segmentation_train.py", line 111, in <module>
    main()
  File "D:\MedSegDiff-master\segmentation_train.py", line 35, in main
    ds = BreastDataset(args, args.data_dir, transform_train)
  File "D:\MedSegDiff-master\guided_diffusion\breastloader.py", line 22, in __init__
    self.label_list = df.iloc[:,2].tolist()
  File "D:\Program Files\Anaconda\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1097, in __getitem__
    return self._getitem_tuple(key)
  File "D:\Program Files\Anaconda\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1594, in _getitem_tuple
    tup = self._validate_tuple_indexer(tup)
  File "D:\Program Files\Anaconda\envs\py39\lib\site-packages\pandas\core\indexing.py", line 904, in _validate_tuple_indexer
    self._validate_key(k, i)
  File "D:\Program Files\Anaconda\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1496, in _validate_key
    self._validate_integer(key, axis)
  File "D:\Program Files\Anaconda\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

Hello, I am conducting this experiment in Windows environment, I am following the same parameter settings as the author, I encountered this problem can not be solved, I ask for your help, thank you!

您好，我是在Windows环境下进行的本次实验，我是按照和作者相同的参数设置，遇到了这个问题无法解决，请求大家帮助，谢谢

**Comment by WuJunde** [comment]
may be your brats csv is wrong

**Comment by DWBSIC** [comment]
> may be your brats csv is wrong

Thank you
谢谢您

**Comment by SiHengHeHSH** [comment]
> 可能是你的小子 csv 错了

What wrong about the csv, I have the same problem, could you please tell me?

**Comment by SiHengHeHSH** [comment]
> > 可能是你的小子 csv 错了
> 
> 谢谢你 谢谢你

I have the same problem, could you please tell me how to repair it?
