### ISSUE TITLE
a problems in the sampling process with BRATS2020 dataset

### ISSUE THREAD

**Issue by liuweichenstart** [WuJunde/MedSegDiff#97]
Traceback (most recent call last):
  File "scripts/segmentation_sample.py", line 191, in <module>
    main()
  File "scripts/segmentation_sample.py", line 114, in main
    sample, x_noisy, org, cal, cal_out = sample_fn(
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/gaussian_diffusion.py", line 562, in p_sample_loop_known
    for sample in self.p_sample_loop_progressive(
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/gaussian_diffusion.py", line 647, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/gaussian_diffusion.py", line 442, in p_sample
    out = self.p_mean_variance(
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/respace.py", line 90, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/gaussian_diffusion.py", line 272, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/respace.py", line 135, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/unet.py", line 1078, in forward
    anch, cal = self.highway_forward(c)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/unet.py", line 1053, in highway_forward
    return self.hwm(x,hs = None)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/unet.py", line 2465, in forward
    x = self.conv_blocks_context[d](x)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/unet.py", line 2196, in forward
    return self.blocks(x)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/MedSegDiff-master_v2/./guided_diffusion/unet.py", line 2119, in forward
    x = self.conv(x)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/liuweichen/anaconda3/envs/lwc/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 4, 3, 3], expected input[1, 3, 256, 256] to have 4 channels, but got 3 channels instead

**Comment by liuweichenstart** [comment]
Thank you very much for taking the time to answer my questions. Based on your feedback, I ran the program again and found that the error results had changed. I am not very clear about this issue either.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuJunde/MedSegDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WuJunde/MedSegDiff] a problems in the sampling process with BRATS2020 dataset (Issue #97)





 
just as it reported, brats is supposed input a 4 channel data with ['t1', 't1ce', 't2', 'flair'], but not 3 channels

**Comment by WuJunde** [comment]
what's your error

**Comment by liuweichenstart** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuJunde/MedSegDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WuJunde/MedSegDiff] a problems in the sampling process with BRATS2020 dataset (Issue #97)





 
what's your error
